/**
 * Ant Design theme for MCP DS Sandbox
 * Generated by scripts/generate-tokens.mjs — do not edit by hand
 * Use: import { ConfigProvider } from 'antd'; import { antTheme } from './ant-theme';
 * @see https://ant.design/docs/react/customize-theme
 */

export const antTheme = {
  "token": {
    "colorPrimary": "#00636A",
    "colorPrimaryHover": "#008585",
    "colorPrimaryActive": "#005055",
    "colorSuccess": "#509c22",
    "colorWarning": "#d46b08",
    "colorError": "#cf1322",
    "colorInfo": "#0958d9",
    "colorText": "rgba(0, 0, 0, 0.88)",
    "colorTextSecondary": "rgba(0, 0, 0, 0.65)",
    "colorTextTertiary": "rgba(0, 0, 0, 0.55)",
    "colorTextQuaternary": "rgba(0, 0, 0, 0.25)",
    "colorTextDisabled": "rgba(0, 0, 0, 0.25)",
    "colorBorder": "#d9d9d9",
    "colorBgContainerDisabled": "rgba(0, 0, 0, 0.04)",
    "colorBorderSecondary": "#f0f0f0",
    "colorBgBase": "#ffffff",
    "colorBgLayout": "#f5f5f5",
    "colorBgContainer": "#ffffff",
    "colorLink": "#00636A",
    "colorLinkHover": "#008585",
    "colorLinkActive": "#005055",
    "borderRadius": 8,
    "borderRadiusSM": 4,
    "borderRadiusLG": 12,
    "fontFamily": "Inter, system-ui, sans-serif",
    "fontSize": 16,
    "fontSizeSM": 14,
    "fontSizeLG": 20,
    "fontSizeXL": 24,
    "lineHeight": 1.5,
    "lineHeightSM": 1.5714285714285714,
    "lineHeightLG": 1.4,
    "controlHeight": 32,
    "controlHeightSM": 24,
    "controlHeightLG": 40,
    "paddingXS": 8,
    "paddingSM": 12,
    "padding": 16,
    "paddingLG": 24,
    "paddingXL": 32,
    "marginXS": 8,
    "marginSM": 12,
    "margin": 16,
    "marginLG": 24,
    "marginXL": 32
  },
  "components": {
    "Alert": {
      "colorInfoBg": "#e6f4ff",
      "colorInfoBorder": "#91caff",
      "colorSuccessBg": "#f0f9ea",
      "colorSuccessBorder": "#c1e7aa",
      "colorWarningBg": "#fff7e6",
      "colorWarningBorder": "#ffd591",
      "colorErrorBg": "#fff1f0",
      "colorErrorBorder": "#ffa39e",
      "borderRadiusLG": 8
    },
    "Button": {
      "primaryColor": "#ffffff",
      "defaultBg": "#ffffff",
      "defaultBorderColor": "#d9d9d9",
      "defaultColor": "rgba(0, 0, 0, 0.88)",
      "borderRadius": 4,
      "controlHeightSM": 24
    },
    "Radio": {
      "radioSize": 16,
      "dotSize": 8,
      "wrapperMarginInlineEnd": 8,
      "dotColorDisabled": "rgba(0, 0, 0, 0.25)",
      "colorPrimary": "#00636A",
      "colorPrimaryHover": "#008585",
      "colorPrimaryActive": "#005055"
    }
  }
} as const;

export type AntTheme = typeof antTheme;

export default antTheme;
