/* Generated by scripts/generate-tokens.mjs — do not edit by hand */

export type SizeToken = { name: string; cssVar: string; value: string };

/** Primitive spacing from tokens/primitives.tokens.json */
export const SPACING_TOKENS: SizeToken[] = [
  {
    "name": "xxs",
    "cssVar": "--primitive-space-xxs",
    "value": "4px"
  },
  {
    "name": "xs",
    "cssVar": "--primitive-space-xs",
    "value": "8px"
  },
  {
    "name": "sm",
    "cssVar": "--primitive-space-sm",
    "value": "12px"
  },
  {
    "name": "base",
    "cssVar": "--primitive-space-base",
    "value": "16px"
  },
  {
    "name": "lg",
    "cssVar": "--primitive-space-lg",
    "value": "24px"
  },
  {
    "name": "xl",
    "cssVar": "--primitive-space-xl",
    "value": "32px"
  },
  {
    "name": "2xl",
    "cssVar": "--primitive-space-2xl",
    "value": "40px"
  },
  {
    "name": "3xl",
    "cssVar": "--primitive-space-3xl",
    "value": "48px"
  }
];

/** Primitive radius from tokens/primitives.tokens.json */
export const RADIUS_TOKENS: SizeToken[] = [
  {
    "name": "2xs",
    "cssVar": "--primitive-radius-2xs",
    "value": "2px"
  },
  {
    "name": "xs",
    "cssVar": "--primitive-radius-xs",
    "value": "4px"
  },
  {
    "name": "sm",
    "cssVar": "--primitive-radius-sm",
    "value": "6px"
  },
  {
    "name": "base",
    "cssVar": "--primitive-radius-base",
    "value": "8px"
  },
  {
    "name": "lg",
    "cssVar": "--primitive-radius-lg",
    "value": "12px"
  }
];

export function formatSizeLabel(name: string, value: string): string {
  return `${name} (${value})`;
}
