/* Generated by scripts/generate-tokens.mjs — do not edit by hand */

export type ColorSwatch = { name: string; cssVar: string };
export type ColorSection = { title: string; swatches: ColorSwatch[] };

/** Semantic colour tokens from tokens/semantics.json */
export const SEMANTIC_COLOR_SECTIONS: ColorSection[] = [
  {
    "title": "Text",
    "swatches": [
      {
        "name": "Text Base",
        "cssVar": "--color-text-base"
      },
      {
        "name": "Text Default",
        "cssVar": "--color-text-default"
      },
      {
        "name": "Text Description",
        "cssVar": "--color-text-description"
      },
      {
        "name": "Text Disabled",
        "cssVar": "--color-text-disabled"
      },
      {
        "name": "Text Heading",
        "cssVar": "--color-text-heading"
      },
      {
        "name": "Text Label",
        "cssVar": "--color-text-label"
      },
      {
        "name": "Text Placeholder",
        "cssVar": "--color-text-placeholder"
      },
      {
        "name": "Text Quarternary",
        "cssVar": "--color-text-quarternary"
      },
      {
        "name": "Text Secondary",
        "cssVar": "--color-text-secondary"
      },
      {
        "name": "Text Tertiary",
        "cssVar": "--color-text-tertiary"
      },
      {
        "name": "Text White",
        "cssVar": "--color-text-white"
      }
    ]
  },
  {
    "title": "Fill",
    "swatches": [
      {
        "name": "Fill Alternative",
        "cssVar": "--color-fill-alternative"
      },
      {
        "name": "Fill Content",
        "cssVar": "--color-fill-content"
      },
      {
        "name": "Fill Content Hover",
        "cssVar": "--color-fill-content-hover"
      },
      {
        "name": "Fill Default",
        "cssVar": "--color-fill-default"
      },
      {
        "name": "Fill Quarternary",
        "cssVar": "--color-fill-quarternary"
      },
      {
        "name": "Fill Secondary",
        "cssVar": "--color-fill-secondary"
      },
      {
        "name": "Fill Tertiary",
        "cssVar": "--color-fill-tertiary"
      }
    ]
  },
  {
    "title": "Icon",
    "swatches": [
      {
        "name": "Icon Default",
        "cssVar": "--color-icon-default"
      },
      {
        "name": "Icon Hover",
        "cssVar": "--color-icon-hover"
      }
    ]
  },
  {
    "title": "Background",
    "swatches": [
      {
        "name": "Bg Base",
        "cssVar": "--color-bg-base"
      },
      {
        "name": "Bg Container",
        "cssVar": "--color-bg-container"
      },
      {
        "name": "Bg Container Dark",
        "cssVar": "--color-bg-container-dark"
      },
      {
        "name": "Bg Container Disabled",
        "cssVar": "--color-bg-container-disabled"
      },
      {
        "name": "Bg Layout",
        "cssVar": "--color-bg-layout"
      },
      {
        "name": "Bg Mask",
        "cssVar": "--color-bg-mask"
      },
      {
        "name": "Bg Spotlight",
        "cssVar": "--color-bg-spotlight"
      },
      {
        "name": "Bg Text Active",
        "cssVar": "--color-bg-text-active"
      },
      {
        "name": "Bg Text Hover",
        "cssVar": "--color-bg-text-hover"
      }
    ]
  },
  {
    "title": "Border",
    "swatches": [
      {
        "name": "Border Default",
        "cssVar": "--color-border-default"
      },
      {
        "name": "Border Secondary",
        "cssVar": "--color-border-secondary"
      },
      {
        "name": "Border Split",
        "cssVar": "--color-border-split"
      }
    ]
  },
  {
    "title": "Primary",
    "swatches": [
      {
        "name": "Primary Active",
        "cssVar": "--color-primary-active"
      },
      {
        "name": "Primary Bg",
        "cssVar": "--color-primary-bg"
      },
      {
        "name": "Primary Bg Hover",
        "cssVar": "--color-primary-bg-hover"
      },
      {
        "name": "Primary Border",
        "cssVar": "--color-primary-border"
      },
      {
        "name": "Primary Border Hover",
        "cssVar": "--color-primary-border-hover"
      },
      {
        "name": "Primary Default",
        "cssVar": "--color-primary-default"
      },
      {
        "name": "Primary Hover",
        "cssVar": "--color-primary-hover"
      },
      {
        "name": "Primary Text",
        "cssVar": "--color-primary-text"
      },
      {
        "name": "Primary Text Active",
        "cssVar": "--color-primary-text-active"
      },
      {
        "name": "Primary Text Hover",
        "cssVar": "--color-primary-text-hover"
      }
    ]
  },
  {
    "title": "System — Success",
    "swatches": [
      {
        "name": "System Success Active",
        "cssVar": "--color-system-success-active"
      },
      {
        "name": "System Success Bg",
        "cssVar": "--color-system-success-bg"
      },
      {
        "name": "System Success Bg Hover",
        "cssVar": "--color-system-success-bg-hover"
      },
      {
        "name": "System Success Border",
        "cssVar": "--color-system-success-border"
      },
      {
        "name": "System Success Border Hover",
        "cssVar": "--color-system-success-border-hover"
      },
      {
        "name": "System Success Default",
        "cssVar": "--color-system-success-default"
      },
      {
        "name": "System Success Hover",
        "cssVar": "--color-system-success-hover"
      },
      {
        "name": "System Success Text",
        "cssVar": "--color-system-success-text"
      },
      {
        "name": "System Success Text Active",
        "cssVar": "--color-system-success-text-active"
      },
      {
        "name": "System Success Text Hover",
        "cssVar": "--color-system-success-text-hover"
      }
    ]
  },
  {
    "title": "System — Warning",
    "swatches": [
      {
        "name": "System Warning Active",
        "cssVar": "--color-system-warning-active"
      },
      {
        "name": "System Warning Bg",
        "cssVar": "--color-system-warning-bg"
      },
      {
        "name": "System Warning Bg Hover",
        "cssVar": "--color-system-warning-bg-hover"
      },
      {
        "name": "System Warning Border",
        "cssVar": "--color-system-warning-border"
      },
      {
        "name": "System Warning Border Hover",
        "cssVar": "--color-system-warning-border-hover"
      },
      {
        "name": "System Warning Default",
        "cssVar": "--color-system-warning-default"
      },
      {
        "name": "System Warning Hover",
        "cssVar": "--color-system-warning-hover"
      },
      {
        "name": "System Warning Outline",
        "cssVar": "--color-system-warning-outline"
      },
      {
        "name": "System Warning Text",
        "cssVar": "--color-system-warning-text"
      },
      {
        "name": "System Warning Text Active",
        "cssVar": "--color-system-warning-text-active"
      },
      {
        "name": "System Warning Text Hover",
        "cssVar": "--color-system-warning-text-hover"
      }
    ]
  },
  {
    "title": "System — Error",
    "swatches": [
      {
        "name": "System Error Active",
        "cssVar": "--color-system-error-active"
      },
      {
        "name": "System Error Bg",
        "cssVar": "--color-system-error-bg"
      },
      {
        "name": "System Error Bg Hover",
        "cssVar": "--color-system-error-bg-hover"
      },
      {
        "name": "System Error Border",
        "cssVar": "--color-system-error-border"
      },
      {
        "name": "System Error Border Hover",
        "cssVar": "--color-system-error-border-hover"
      },
      {
        "name": "System Error Default",
        "cssVar": "--color-system-error-default"
      },
      {
        "name": "System Error Hover",
        "cssVar": "--color-system-error-hover"
      },
      {
        "name": "System Error Outline",
        "cssVar": "--color-system-error-outline"
      },
      {
        "name": "System Error Text",
        "cssVar": "--color-system-error-text"
      },
      {
        "name": "System Error Text Active",
        "cssVar": "--color-system-error-text-active"
      },
      {
        "name": "System Error Text Hover",
        "cssVar": "--color-system-error-text-hover"
      }
    ]
  },
  {
    "title": "System — Info",
    "swatches": [
      {
        "name": "System Info Active",
        "cssVar": "--color-system-info-active"
      },
      {
        "name": "System Info Bg",
        "cssVar": "--color-system-info-bg"
      },
      {
        "name": "System Info Bg Hover",
        "cssVar": "--color-system-info-bg-hover"
      },
      {
        "name": "System Info Border",
        "cssVar": "--color-system-info-border"
      },
      {
        "name": "System Info Border Hover",
        "cssVar": "--color-system-info-border-hover"
      },
      {
        "name": "System Info Default",
        "cssVar": "--color-system-info-default"
      },
      {
        "name": "System Info Hover",
        "cssVar": "--color-system-info-hover"
      },
      {
        "name": "System Info Text",
        "cssVar": "--color-system-info-text"
      },
      {
        "name": "System Info Text Active",
        "cssVar": "--color-system-info-text-active"
      },
      {
        "name": "System Info Text Hover",
        "cssVar": "--color-system-info-text-hover"
      }
    ]
  },
  {
    "title": "System — Link",
    "swatches": [
      {
        "name": "System Link Active",
        "cssVar": "--color-system-link-active"
      },
      {
        "name": "System Link Default",
        "cssVar": "--color-system-link-default"
      },
      {
        "name": "System Link Hover",
        "cssVar": "--color-system-link-hover"
      }
    ]
  },
  {
    "title": "System — Control",
    "swatches": [
      {
        "name": "System Control Bg Active",
        "cssVar": "--color-system-control-bg-active"
      },
      {
        "name": "System Control Bg Active Disabled",
        "cssVar": "--color-system-control-bg-active-disabled"
      },
      {
        "name": "System Control Bg Active Hover",
        "cssVar": "--color-system-control-bg-active-hover"
      },
      {
        "name": "System Control Bg Hover",
        "cssVar": "--color-system-control-bg-hover"
      },
      {
        "name": "System Control Bg Menu",
        "cssVar": "--color-system-control-bg-menu"
      },
      {
        "name": "System Control Bg Option Hover",
        "cssVar": "--color-system-control-bg-option-hover"
      },
      {
        "name": "System Control Bg Option Select",
        "cssVar": "--color-system-control-bg-option-select"
      },
      {
        "name": "System Control Bg Option Selected",
        "cssVar": "--color-system-control-bg-option-selected"
      },
      {
        "name": "System Control Bg Unselected",
        "cssVar": "--color-system-control-bg-unselected"
      },
      {
        "name": "System Control Border",
        "cssVar": "--color-system-control-border"
      },
      {
        "name": "System Control Scrollbar",
        "cssVar": "--color-system-control-scrollbar"
      },
      {
        "name": "System Control Selected",
        "cssVar": "--color-system-control-selected"
      },
      {
        "name": "System Control Tmp Border",
        "cssVar": "--color-system-control-tmp-border"
      }
    ]
  }
];

/** Data colour primitives from tokens/primitives.tokens.json */
export const DATA_COLOR_SECTIONS: ColorSection[] = [
  {
    "title": "Data colour — Blue",
    "swatches": [
      {
        "name": "Blue 1",
        "cssVar": "--primitive-data-color-blue-1"
      },
      {
        "name": "Blue 2",
        "cssVar": "--primitive-data-color-blue-2"
      },
      {
        "name": "Blue 3",
        "cssVar": "--primitive-data-color-blue-3"
      },
      {
        "name": "Blue 4",
        "cssVar": "--primitive-data-color-blue-4"
      },
      {
        "name": "Blue 5",
        "cssVar": "--primitive-data-color-blue-5"
      },
      {
        "name": "Blue 6",
        "cssVar": "--primitive-data-color-blue-6"
      },
      {
        "name": "Blue 7",
        "cssVar": "--primitive-data-color-blue-7"
      },
      {
        "name": "Blue 8",
        "cssVar": "--primitive-data-color-blue-8"
      }
    ]
  },
  {
    "title": "Data colour — Cyan",
    "swatches": [
      {
        "name": "Cyan 1",
        "cssVar": "--primitive-data-color-cyan-1"
      },
      {
        "name": "Cyan 2",
        "cssVar": "--primitive-data-color-cyan-2"
      },
      {
        "name": "Cyan 3",
        "cssVar": "--primitive-data-color-cyan-3"
      },
      {
        "name": "Cyan 4",
        "cssVar": "--primitive-data-color-cyan-4"
      },
      {
        "name": "Cyan 5",
        "cssVar": "--primitive-data-color-cyan-5"
      },
      {
        "name": "Cyan 6",
        "cssVar": "--primitive-data-color-cyan-6"
      },
      {
        "name": "Cyan 7",
        "cssVar": "--primitive-data-color-cyan-7"
      },
      {
        "name": "Cyan 8",
        "cssVar": "--primitive-data-color-cyan-8"
      }
    ]
  },
  {
    "title": "Data colour — Green",
    "swatches": [
      {
        "name": "Green 1",
        "cssVar": "--primitive-data-color-green-1"
      },
      {
        "name": "Green 2",
        "cssVar": "--primitive-data-color-green-2"
      },
      {
        "name": "Green 3",
        "cssVar": "--primitive-data-color-green-3"
      },
      {
        "name": "Green 4",
        "cssVar": "--primitive-data-color-green-4"
      },
      {
        "name": "Green 5",
        "cssVar": "--primitive-data-color-green-5"
      },
      {
        "name": "Green 6",
        "cssVar": "--primitive-data-color-green-6"
      },
      {
        "name": "Green 7",
        "cssVar": "--primitive-data-color-green-7"
      },
      {
        "name": "Green 8",
        "cssVar": "--primitive-data-color-green-8"
      }
    ]
  },
  {
    "title": "Data colour — Grey",
    "swatches": [
      {
        "name": "Grey 1",
        "cssVar": "--primitive-data-color-grey-1"
      },
      {
        "name": "Grey 2",
        "cssVar": "--primitive-data-color-grey-2"
      },
      {
        "name": "Grey 3",
        "cssVar": "--primitive-data-color-grey-3"
      },
      {
        "name": "Grey 4",
        "cssVar": "--primitive-data-color-grey-4"
      },
      {
        "name": "Grey 5",
        "cssVar": "--primitive-data-color-grey-5"
      },
      {
        "name": "Grey 6",
        "cssVar": "--primitive-data-color-grey-6"
      },
      {
        "name": "Grey 7",
        "cssVar": "--primitive-data-color-grey-7"
      },
      {
        "name": "Grey 8",
        "cssVar": "--primitive-data-color-grey-8"
      }
    ]
  },
  {
    "title": "Data colour — Orange",
    "swatches": [
      {
        "name": "Orange 1",
        "cssVar": "--primitive-data-color-orange-1"
      },
      {
        "name": "Orange 2",
        "cssVar": "--primitive-data-color-orange-2"
      },
      {
        "name": "Orange 3",
        "cssVar": "--primitive-data-color-orange-3"
      },
      {
        "name": "Orange 4",
        "cssVar": "--primitive-data-color-orange-4"
      },
      {
        "name": "Orange 5",
        "cssVar": "--primitive-data-color-orange-5"
      },
      {
        "name": "Orange 6",
        "cssVar": "--primitive-data-color-orange-6"
      },
      {
        "name": "Orange 7",
        "cssVar": "--primitive-data-color-orange-7"
      },
      {
        "name": "Orange 8",
        "cssVar": "--primitive-data-color-orange-8"
      }
    ]
  },
  {
    "title": "Data colour — Pink",
    "swatches": [
      {
        "name": "Pink 1",
        "cssVar": "--primitive-data-color-pink-1"
      },
      {
        "name": "Pink 2",
        "cssVar": "--primitive-data-color-pink-2"
      },
      {
        "name": "Pink 3",
        "cssVar": "--primitive-data-color-pink-3"
      },
      {
        "name": "Pink 4",
        "cssVar": "--primitive-data-color-pink-4"
      },
      {
        "name": "Pink 5",
        "cssVar": "--primitive-data-color-pink-5"
      },
      {
        "name": "Pink 6",
        "cssVar": "--primitive-data-color-pink-6"
      },
      {
        "name": "Pink 7",
        "cssVar": "--primitive-data-color-pink-7"
      },
      {
        "name": "Pink 8",
        "cssVar": "--primitive-data-color-pink-8"
      }
    ]
  },
  {
    "title": "Data colour — Purple",
    "swatches": [
      {
        "name": "Purple 1",
        "cssVar": "--primitive-data-color-purple-1"
      },
      {
        "name": "Purple 2",
        "cssVar": "--primitive-data-color-purple-2"
      },
      {
        "name": "Purple 3",
        "cssVar": "--primitive-data-color-purple-3"
      },
      {
        "name": "Purple 4",
        "cssVar": "--primitive-data-color-purple-4"
      },
      {
        "name": "Purple 5",
        "cssVar": "--primitive-data-color-purple-5"
      },
      {
        "name": "Purple 6",
        "cssVar": "--primitive-data-color-purple-6"
      },
      {
        "name": "Purple 7",
        "cssVar": "--primitive-data-color-purple-7"
      },
      {
        "name": "Purple 8",
        "cssVar": "--primitive-data-color-purple-8"
      }
    ]
  },
  {
    "title": "Data colour — Red",
    "swatches": [
      {
        "name": "Red 1",
        "cssVar": "--primitive-data-color-red-1"
      },
      {
        "name": "Red 2",
        "cssVar": "--primitive-data-color-red-2"
      },
      {
        "name": "Red 3",
        "cssVar": "--primitive-data-color-red-3"
      },
      {
        "name": "Red 4",
        "cssVar": "--primitive-data-color-red-4"
      },
      {
        "name": "Red 5",
        "cssVar": "--primitive-data-color-red-5"
      },
      {
        "name": "Red 6",
        "cssVar": "--primitive-data-color-red-6"
      },
      {
        "name": "Red 7",
        "cssVar": "--primitive-data-color-red-7"
      },
      {
        "name": "Red 8",
        "cssVar": "--primitive-data-color-red-8"
      }
    ]
  },
  {
    "title": "Data colour — Yellow",
    "swatches": [
      {
        "name": "Yellow 1",
        "cssVar": "--primitive-data-color-yellow-1"
      },
      {
        "name": "Yellow 2",
        "cssVar": "--primitive-data-color-yellow-2"
      },
      {
        "name": "Yellow 3",
        "cssVar": "--primitive-data-color-yellow-3"
      },
      {
        "name": "Yellow 4",
        "cssVar": "--primitive-data-color-yellow-4"
      },
      {
        "name": "Yellow 5",
        "cssVar": "--primitive-data-color-yellow-5"
      },
      {
        "name": "Yellow 6",
        "cssVar": "--primitive-data-color-yellow-6"
      },
      {
        "name": "Yellow 7",
        "cssVar": "--primitive-data-color-yellow-7"
      },
      {
        "name": "Yellow 8",
        "cssVar": "--primitive-data-color-yellow-8"
      }
    ]
  }
];
